name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPStan
      id: phpstan
      env: 
        PHP_STAN_LEVEL: 6
      run: |
        echo "PHP_STAN_ERRORS=$(vendor/bin/phpstan --no-progress --error-format=github  analyse -l ${{env.PHP_STAN_LEVEL}} src" >> $GITHUB_ENV
        if [ -n "$PHP_STAN_ERRORS" ]; then
          exit 1
        fi
      continue-on-error: true

    - uses: mainmatter/continue-on-error-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        outcome: ${{ steps.phpstan.outcome }}
        test-id: PHPStan -> ${{ env.PHP_STAN_ERRORS }}

    - name: Run test suite
      id: tests
      run: |
        echo "PHPUNIT_ERRORS=$(vendor/bin/pest --no-coverage | grep 'Tests:')" >> $GITHUB_ENV
      continue-on-error: true

    - uses: mainmatter/continue-on-error-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        outcome: ${{ steps.tests.outcome }}
        test-id: PHP Unit -> ${{ env.PHPUNIT_ERRORS }}
