name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  phpstan:
    uses: clebsonsh/workflows/php-stan.yml@main
  phpunit:
    uses: clebsonsh/workflows/php-unit.yml@main
