name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    env:
      PHP_STAN_LEVEL: 6

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPStan
      id: phpstan
      run: |
        echo "PHP_STAN_ERRORS_COUNT=$(vendor/bin/phpstan --no-progress --error-format=github  analyse -l ${{env.PHP_STAN_LEVEL}} src | grep ::error | wc -l)" >> $GITHUB_ENV
        if [ ${{env.PHP_STAN_ERRORS_COUNT}} != 0 ]; then exit 1; fi
      continue-on-error: true

    - uses: mainmatter/continue-on-error-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        outcome: ${{ steps.phpstan.outcome }}
        test-id: PHPStan -> ${{ env.PHP_STAN_ERRORS_COUNT }} errors found

    - name: Run test suite
      id: tests
      run: |
        echo "PHPUNIT_ERRORS=$(vendor/bin/pest --no-coverage | grep 'Tests:')" >> $GITHUB_ENV
        if [ -z "${{env.PHPUNIT_ERRORS}}" ]; then exit 1; fi
      continue-on-error: true

    - uses: mainmatter/continue-on-error-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        outcome: ${{ steps.tests.outcome }}
        test-id: PHP Unit -> ${{ env.PHPUNIT_ERRORS }}

    - name: Break the build if there are errors
      run: |
        if [ ${{env.PHP_STAN_ERRORS_COUNT}} -gt 0 ]; then exit 1; fi
        if [ -z "${{env.PHPUNIT_ERRORS}}" ]; then exit 1; fi
