name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPStan
      id: phpstan
      run: vendor/bin/phpstan analyse -l 0 src
      continue-on-error: true

    - uses: mainmatter/continue-on-error-comment@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        outcome: ${{ steps.phpstan.outcome }}
        test-id: PHPStan found errors

    - name: Run test suite
      id: test
      run: vendor/bin/pest
