name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  phpstan:
    uses: clebsonsh/workflows/.github/workflows/php-stan.yml@main
    with:
      PHP_STAN_LEVEL: 7
      STOP_ON_ERROR: false
  phpunit:
    uses: clebsonsh/workflows/.github/workflows/php-unit.yml@main
    with:
      STOP_ON_ERROR: true
