name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    env:
      PHP_STAN_LEVEL: 0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPStan
      id: phpstan
      run: |
        echo "PHP_STAN_ERRORS=$(vendor/bin/phpstan --no-progress --error-format=github  analyse -l ${{env.PHP_STAN_LEVEL}} src | grep ::error)" >> $GITHUB_ENV
      continue-on-error: true
    
    - name: PHP Stan Erros Count and Show Errors
      run: |
        echo ${{env.PHP_STAN_ERRORS}}
        echo "PHP_STAN_ERRORS_COUNT=$(echo '${{env.PHP_STAN_ERRORS}}' | grep -o -i ::error | wc -l)" >> $GITHUB_ENV

    - name: Comment PR
      if: env.PHP_STAN_ERRORS_COUNT > 0
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          PHPStan -> ${{env.PHP_STAN_ERRORS_COUNT}} errors found. Please fix them before merging.


    - name: Run test suite
      id: tests
      run: |
        echo "PHP_UNIT_ERRORS_COUNT=$(vendor/bin/pest --no-coverage | grep FAILED | wc -l)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Comment PR
      if: env.PHP_UNIT_ERRORS_COUNT > 0
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          PHP Unit -> ${{ env.PHP_UNIT_ERRORS_COUNT }} errors found. Please fix them before merging.

    - name: Break the build if there are errors
      run: |
        if [ ${{env.PHP_STAN_ERRORS_COUNT}} -gt 0 ]; then exit 1; fi
        if [ ${{env.PHP_UNIT_ERRORS_COUNT}} -gt 0 ]; then exit 1; fi
